services:
  - type: web
    name: roseen-api
    runtime: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: checksPass
    healthCheckPath: /api/health
    domains:
      - api.roseen.ru
    renderSubdomainPolicy: enabled
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: S3_BUCKET
        value: roseen-attachments
      - key: AWS_ENDPOINT_URL_S3
        value: https://br-crimson-bread-b2b6yi3f.storage.c-6.eu-central-1.aws.neon.tech
      - key: AWS_REGION
        value: eu-central-1
      - key: NEON_STORAGE_FORCE_PATH_STYLE
        value: "true"
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: FRONTEND_ORIGIN
        value: https://roseen.ru,https://www.roseen.ru,https://vg6ts6ffdk-svg.github.io
      - key: ADMIN_EMAIL
        value: admin@roseen.ru
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
