import test from 'node:test';
import assert from 'node:assert/strict';
import { validateCatalog, searchCatalog, compatibilityFor, quoteCart, evaluateLaunchReadiness, LAUNCH_REQUIREMENTS } from '../commerce/catalog.mjs';
// Synthetic fixtures only. These are not customer-facing product offers.
const fixture = () => ({ version: 1, currency: 'RUB', products: [{ id: 'test-part', sku: 'TEST-001', name: 'Синтетическая тестовая деталь', category: 'test', manufacturer: 'Test manufacturer', unit: 'шт.', state: 'published', availability: 'in_stock', priceMinor: 15001, stock: 5, oem: ['TEST-OEM-01'], sourceRef: 'test-fixture:not-a-real-product', verifiedAt: '2026-09-20T00:00:00Z', compatibility: [{ equipmentBrand: 'Test brand', model: 'Test model', revision: null, status: 'confirmed', sourceRef: 'test-fixture:not-real-evidence' }] }] });
test('empty catalogue is valid and contains no pretend products', () => { const c = {version:1,currency:'RUB',products:[]}; assert.equal(searchCatalog(c).length,0); assert.equal(quoteCart(c,[]).goodsReady,false); });
test('published goods require provenance and timestamp', () => { const c=fixture(); delete c.products[0].sourceRef; assert.throws(()=>validateCatalog(c),/Publication/); });
test('unknown price is not represented by zero', () => { const c=fixture(); c.products[0].priceMinor=null; validateCatalog(c); assert.equal(quoteCart(c,[{id:'test-part',quantity:1}]).issues[0].code,'PRICE_ON_REQUEST'); c.products[0].priceMinor=0; assert.throws(()=>validateCatalog(c),/Price/); });
test('duplicates and invalid identifiers are rejected', () => { const c=fixture(); c.products.push(structuredClone(c.products[0])); assert.throws(()=>validateCatalog(c),/Duplicate/); c.products.pop();c.products[0].id='<script>';assert.throws(()=>validateCatalog(c),/identifier/); });
test('draft and archived goods are not searchable', () => { for(const state of ['draft','archived']){const c=fixture();c.products[0].state=state;assert.equal(searchCatalog(c).length,0);} });
test('SKU and OEM search are case-insensitive', () => { assert.equal(searchCatalog(fixture(),{query:'test-001'}).length,1);assert.equal(searchCatalog(fixture(),{query:'test-oem-01'}).length,1); });
test('unproven compatibility stays unknown and is excluded by equipment filter', () => { const c=fixture();assert.equal(compatibilityFor(c.products[0],{brand:'Test brand',model:'Different model'}),'unknown');assert.equal(searchCatalog(c,{equipment:{brand:'Test brand',model:'Different model'}}).length,0); });
test('revision-specific fit is not generalized to all revisions', () => { const p=fixture().products[0];p.compatibility[0].revision='A';assert.equal(compatibilityFor(p,{brand:'Test brand',model:'Test model'}),'unknown');assert.equal(compatibilityFor(p,{brand:'Test brand',model:'Test model',revision:'A'}),'confirmed');assert.equal(compatibilityFor(p,{brand:'Test brand',model:'Test model',revision:'B'}),'unknown'); });
test('compatibility conclusion requires evidence', () => { const c=fixture();delete c.products[0].compatibility[0].sourceRef;assert.throws(()=>validateCatalog(c),/evidence/); });
test('cart ignores spoofed client prices and uses integer kopecks', () => { const r=quoteCart(fixture(),[{id:'test-part',quantity:2,priceMinor:1,totalMinor:2,stock:9999}]);assert.equal(r.subtotalMinor,30002);assert.equal(r.checkoutAuthorized,false); });
test('duplicate cart lines are consolidated and stock is rechecked', () => { const c=fixture();assert.equal(quoteCart(c,[{id:'test-part',quantity:2},{id:'test-part',quantity:2}]).lines[0].quantity,4);assert.equal(quoteCart(c,[{id:'test-part',quantity:3},{id:'test-part',quantity:3}]).subtotalMinor,null); });
test('fractional, negative and excessive quantities are rejected', () => { for(const quantity of [0,-1,1.5,100,NaN,Infinity]) assert.throws(()=>quoteCart(fixture(),[{id:'test-part',quantity}]),/cart line/); });
test('unknown availability cannot be purchased', () => { const c=fixture();c.products[0].availability='unknown';c.products[0].stock=null;assert.equal(quoteCart(c,[{id:'test-part',quantity:1}]).goodsReady,false); });
test('checkout is fail-closed and does not trust truthy strings or inherited flags', () => { assert.equal(evaluateLaunchReadiness().checkoutEnabled,false);const all=Object.fromEntries(LAUNCH_REQUIREMENTS.map(k=>[k,true]));assert.equal(evaluateLaunchReadiness(all).checkoutEnabled,true);assert.equal(evaluateLaunchReadiness(Object.create(all)).checkoutEnabled,false);all.sellerVerified='true';assert.equal(evaluateLaunchReadiness(all).checkoutEnabled,false); });
