import test from 'node:test';import assert from 'node:assert/strict';import Database from 'better-sqlite3';
import {createOrderSnapshot,transitionOrder,applyPaymentState} from '../commerce/orders.mjs';
import {createSqliteOrderRepository} from '../commerce/order-repository.mjs';
const order=(id='O1',key='ABCDEFGHIJKLMNOP')=>createOrderSnapshot({id,customerId:'C1',idempotencyKey:key,goodsSubtotalMinor:10000,lines:[{id:'P1',sku:'S1',name:'Part',quantity:1,unitPriceMinor:10000}]});
test('persistent repository replays identical idempotent create',async()=>{const db=new Database(':memory:');const r=createSqliteOrderRepository(db);const a=order();assert.equal((await r.create(a)).replay,false);assert.equal((await r.create({...a,createdAt:new Date().toISOString()})).replay,true);db.close();});
test('same idempotency key with different payload is rejected',async()=>{const db=new Database(':memory:');const r=createSqliteOrderRepository(db);await r.create(order());await assert.rejects(()=>r.create(order('O2')),e=>e.code==='ORDER_CONFLICT');db.close();});
test('customer listing is ownership-scoped',async()=>{const db=new Database(':memory:');const r=createSqliteOrderRepository(db);await r.create(order());await r.create(createOrderSnapshot({id:'O2',customerId:'C2',idempotencyKey:'QRSTUVWXYZabcdef',goodsSubtotalMinor:10000,lines:[{id:'P1',sku:'S1',name:'Part',quantity:1,unitPriceMinor:10000}]}));assert.deepEqual((await r.listByCustomer('C1')).map(x=>x.id),['O1']);db.close();});
test('compare-and-swap prevents stale state overwrite',async()=>{const db=new Database(':memory:');const r=createSqliteOrderRepository(db);const a=order();await r.create(a);const b=transitionOrder(a,'awaiting_payment');await r.replaceState(b,{status:'draft',paymentStatus:'not_started'});await assert.rejects(()=>r.replaceState({...b,paymentStatus:'pending'},{status:'draft',paymentStatus:'not_started'}),e=>e.code==='ORDER_CONFLICT');db.close();});
test('verified payment state can be persisted independently from order state',async()=>{const db=new Database(':memory:');const r=createSqliteOrderRepository(db);const a=transitionOrder(order(),'awaiting_payment');await r.create(a);const b=applyPaymentState(a,'succeeded',{verified:true});await r.replaceState(b,{status:'awaiting_payment',paymentStatus:'not_started'});assert.equal((await r.get('O1')).paymentStatus,'succeeded');db.close();});
