import fs from 'node:fs';
import { categories, publicCatalog, categoryPage } from './settings.mjs';
import { formatPrice, serviceLink, availabilityLabel } from '../store-core.js';
export const esc = x => String(x ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const option = (value, name, selected = false) => `<option value="${esc(value)}"${selected ? ' selected' : ''}>${esc(name)}</option>`;
const notice = '<div class="store-notice"><span class="status-dot" aria-hidden="true"></span><p><strong>Каталог на подготовке.</strong> Оформление и оплата заказов ещё не подключены.</p></div>';
const empty = `<div class="store-empty"><span class="store-empty-mark" aria-hidden="true">↗</span><h2>Проверенные товары<br>ещё не добавлены.</h2><p>Артикулы, цены и совместимость проходят проверку перед публикацией. Пока можно передать модель оборудования и задачу инженеру.</p><a class="btn btn-primary" data-selection-link href="${serviceLink()}">Запросить подбор ↗</a></div>`;
export function card(p) {
  return `<article class="product-card"><a href="${esc(p.url)}" class="product-link">${p.image ? `<img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy" width="640" height="480">` : '<div class="product-no-image">Фото товара не добавлено</div>'}<span class="product-sku">${esc(p.sku)}</span><h3>${esc(p.name)}</h3></a><p class="product-maker">${esc(p.manufacturer)}</p><span class="product-availability">${availabilityLabel(p.availability)}</span><strong class="product-price">${formatPrice(p.priceMinor)}</strong><span class="product-unit">за ${esc(p.unit)}</span><a class="product-details" href="${esc(p.url)}">Характеристики и подбор ↗</a></article>`;
}
function shell(title, main, file) {
  const source = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
  const header = source.match(/<header\b[\s\S]*?<\/header>/)?.[0];
  const footer = source.match(/<footer\b[\s\S]*?<\/footer>/)?.[0];
  if (!header || !footer) throw new Error('Public site shell missing');
  return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — РОСИН</title><meta name="description" content="Каталог запчастей и расходных материалов ROSEEN. Подбор по артикулу и оборудованию."><meta name="robots" content="noindex,nofollow"><link rel="icon" href="favicon.svg"><link rel="canonical" href="https://roseen.ru/${esc(file)}"><link rel="stylesheet" href="style.css"><script src="api-config.js" defer></script><script src="script.js" defer></script></head><body><a class="skip-link" href="#main">Перейти к содержимому</a>${header}<main id="main" class="store-main">${main}</main>${footer}</body></html>`;
}
function searchForm(category, products) {
  const manufacturers = [...new Set(products.map(p => p.manufacturer))].sort();
  return `<form class="store-search" id="catalog-search" data-catalog-search method="get" action="${category ? categoryPage(category.id) : 'shop.html'}">
<div class="catalog-query"><label for="q">Артикул, название или OEM</label><div class="query-row"><input type="search" id="q" name="q" maxlength="200" placeholder="Введите артикул или название детали" autocomplete="off"><button class="btn btn-primary" type="submit">Найти</button></div></div>
<details class="store-filters"><summary>Подбор по оборудованию и фильтры <span aria-hidden="true">+</span></summary>
<div class="store-filter-grid">
<div class="field"><label for="equipmentBrand">Бренд оборудования</label><input id="equipmentBrand" name="equipmentBrand" maxlength="100" placeholder="Производитель оборудования"></div>
<div class="field"><label for="equipment-model">Модель</label><input id="equipment-model" name="model" maxlength="100" placeholder="Точная модель"></div>
<div class="field"><label for="revision">Ревизия / исполнение</label><input id="revision" name="revision" maxlength="100" placeholder="Если известно"></div>
<div class="field"><label for="category">Категория</label><select id="category" name="category">${option('', 'Все категории')}${categories.map(c => option(c.id, c.name, c.id === category?.id)).join('')}</select></div>
<div class="field"><label for="manufacturer">Производитель детали</label><select id="manufacturer" name="manufacturer">${option('', 'Все производители')}${manufacturers.map(m => option(m, m)).join('')}</select></div>
<div class="field"><label for="availability">Наличие</label><select id="availability" name="availability">${option('', 'Все статусы')}${['in_stock', 'out_of_stock', 'on_request', 'unknown'].map(k => option(k, availabilityLabel(k))).join('')}</select></div>
<div class="field"><label for="min">Цена от, ₽</label><input id="min" name="min" inputmode="decimal" maxlength="12" placeholder="От"></div><div class="field"><label for="max">Цена до, ₽</label><input id="max" name="max" inputmode="decimal" maxlength="12" placeholder="До"></div>
</div><p class="compatibility-note">При выборе оборудования показываем только подтверждённую совместимость. Укажите бренд и модель; ревизия помогает исключить неподходящие исполнения.</p><button class="btn btn-ghost" type="submit">Применить фильтры</button></details>
<div class="catalog-toolbar"><p id="catalog-count" role="status" aria-live="polite">${products.length} позиций</p><div class="catalog-sort"><label for="sort">Сортировка</label><select id="sort" name="sort">${option('name', 'По названию')}${option('price-asc', 'Сначала дешевле')}${option('price-desc', 'Сначала дороже')}</select></div><a data-reset-search href="${category ? categoryPage(category.id) : 'shop.html'}">Сбросить</a></div>
</form>`;
}
function catalogPage(data, category = null) {
  const products = category ? data.products.filter(p => p.category === category.id) : data.products;
  const hero = category ? `<nav class="store-breadcrumb" aria-label="Хлебные крошки"><a href="shop.html">Магазин</a><span aria-hidden="true">/</span><span>${esc(category.name)}</span></nav><h1>${esc(category.name)}</h1><p class="lead">${esc(category.detail)}. Совместимость проверяется для конкретной модели и исполнения.</p>` : `<div class="store-hero-grid"><div><div class="eyebrow">ЗАПЧАСТИ · РАСХОДНИКИ · КОМПЛЕКТУЮЩИЕ</div><h1>Точная деталь.<br><em>Для вашей техники.</em></h1><p class="lead">Поиск по артикулу и оборудованию.<br>Совместимость — не предположение, а результат проверки.</p><a class="store-text-link" href="#catalog">Перейти к каталогу ↓</a></div><aside class="selection-guide"><span class="guide-eyebrow">КАК ПОДОБРАТЬ</span><div><b>01</b><p><strong>Знаете артикул?</strong><span>Найдите деталь по SKU или OEM-коду.</span></p></div><div><b>02</b><p><strong>Есть модель техники?</strong><span>Уточните бренд, модель и исполнение.</span></p></div><div><b>03</b><p><strong>Нужна проверка?</strong><span>Передайте задачу сервисному инженеру.</span></p></div><a href="${serviceLink()}">Запросить подбор ↗</a></aside></div>`;
  const categoryLinks = categories.map((c, i) => `<a href="${categoryPage(c.id)}" class="store-category${c.id === category?.id ? ' selected' : ''}"${c.id === category?.id ? ' aria-current="page"' : ''}><span class="category-number">${String(i + 1).padStart(2, '0')}</span><span><strong>${esc(c.name)}</strong><small>${data.products.filter(p => p.category === c.id).length} позиций</small></span><span aria-hidden="true">↗</span></a>`).join('');
  return shell(category?.name || 'Магазин', `<div class="container">${notice}<section class="store-hero">${hero}</section><nav class="store-categories" aria-label="Категории каталога">${categoryLinks}</nav><section id="catalog" class="store-catalog" data-category="${category?.id || ''}"><div class="store-section-title"><h2>${category ? 'Товары категории' : 'Каталог'}</h2><span>Подбор без догадок</span></div>${searchForm(category, products)}<noscript><p class="store-warning">Интерактивный поиск требует JavaScript. Категории и карточки доступны по ссылкам ниже; подбор также можно запросить через сервис.</p></noscript><div id="catalog-results" class="product-grid">${products.length ? products.map(card).join('') : empty}</div><nav id="catalog-pagination" class="catalog-pagination" aria-label="Страницы каталога"></nav></section><section class="store-service-link"><div><h2>Не уверены, что дело в детали?</h2><p>Сначала диагностика. Затем — подбор и согласование работ.</p></div><a class="btn btn-ghost" href="contacts.html#request">Обсудить с сервисом ↗</a></section></div>`, category ? categoryPage(category.id) : 'shop.html');
}
function product(p) {
  const canAdd = p.priceMinor !== null && p.availability === 'in_stock' && p.stock > 0;
  return shell(p.name, `<div class="container">${notice}<nav class="store-breadcrumb" aria-label="Хлебные крошки"><a href="shop.html">Магазин</a><span>/</span><a href="${categoryPage(p.category)}">${esc(categories.find(c => c.id === p.category)?.name || p.category)}</a><span>/</span><span>${esc(p.sku)}</span></nav><section class="store-product"><div class="product-visual">${p.image ? `<img src="${esc(p.image)}" alt="${esc(p.name)}" width="640" height="480">` : '<div class="product-no-image">Фото товара не добавлено</div>'}</div><div class="product-info"><span class="eyebrow">АРТИКУЛ ${esc(p.sku)}</span><h1>${esc(p.name)}</h1><p>${esc(p.manufacturer)}</p><p class="product-price">${formatPrice(p.priceMinor)} <small>за ${esc(p.unit)}</small></p><span class="product-availability">${availabilityLabel(p.availability)}</span><p class="muted">${esc(p.description)}</p>${canAdd ? `<div class="product-buy"><label for="product-quantity">Количество</label><input id="product-quantity" type="number" min="1" max="${Math.min(p.stock, 99)}" value="1"><button class="btn btn-primary" data-add-cart="${esc(p.id)}" type="button" disabled>В корзину</button></div>` : ''}<p id="product-status" role="status" aria-live="polite"></p><a class="store-text-link" href="${esc(serviceLink({ sku: p.sku }))}">Уточнить совместимость ↗</a><a class="store-text-link" href="${esc(serviceLink({ sku: p.sku, mode: 'installation' }))}">Нужна установка ↗</a><noscript><p>Корзина требует JavaScript. Подбор доступен по ссылке выше.</p></noscript></div></section><section class="product-specs"><h2>Совместимость</h2>${p.compatibility.length ? `<ul>${p.compatibility.map(c => `<li>${esc(c.equipmentBrand)} ${esc(c.model)}${c.revision ? ' / ' + esc(c.revision) : ''} — <strong>${({ confirmed: 'подтверждена', incompatible: 'не подходит', unknown: 'требует проверки' })[c.status] || 'требует проверки'}</strong></li>`).join('')}</ul>` : '<p>Подтверждённые модели не указаны. Запросите проверку у инженера.</p>'}<h2>Артикулы производителя / OEM</h2><p>${p.oem.length ? p.oem.map(esc).join(' · ') : 'Не указаны'}</p><h2>Доставка и оформление</h2><p>Оформление заказов в этой версии закрыто. Стоимость доставки, сроки и условия продажи не определены и не включены в стоимость товаров.</p></section></div>`, p.url);
}
export function renderStoreFiles(data = publicCatalog()) {
  const files = new Map();
  files.set('shop.html', catalogPage(data));
  categories.forEach(c => files.set(categoryPage(c.id), catalogPage(data, c)));
  data.products.forEach(p => files.set(p.url, product(p)));
  files.set('account.html', shell('Личный кабинет', `<div class="container">${notice}<nav class="store-breadcrumb" aria-label="Хлебные крошки"><a href="shop.html">Магазин</a><span>/</span><span>Личный кабинет</span></nav><section class="account-hero"><span class="eyebrow">КЛИЕНТСКИЙ КАБИНЕТ</span><h1>Техника, сервис и заказы<br><em>в одном месте.</em></h1><p class="lead">Интерфейс кабинета подготовлен. Авторизация клиента и персональные данные будут включены только после подключения постоянного commerce-backend и проверки разграничения доступа.</p></section><section class="account-grid" aria-label="Разделы будущего кабинета"><article><span>01</span><h2>Моё оборудование</h2><p>Бренд, модель, ревизия и подтверждённая совместимость деталей.</p></article><article><span>02</span><h2>Сервис</h2><p>История обращений и согласований после подтверждения принадлежности аккаунту.</p></article><article><span>03</span><h2>Заказы</h2><p>Состав, документы и статусы после запуска реального order backend.</p></article><article><span>04</span><h2>Документы</h2><p>Счета и закрывающие документы только из подтверждённой учётной системы.</p></article></section><div class="account-locked"><strong>Вход пока закрыт</strong><p>Это Preview структуры кабинета. Фиктивная регистрация и тестовые клиентские данные в production не создаются.</p><a class="btn btn-ghost" href="contacts.html#request">Связаться с сервисом ↗</a></div></div>`, 'account.html'));
  files.set('cart.html', shell('Корзина', `<div class="container">${notice}<nav class="store-breadcrumb" aria-label="Хлебные крошки"><a href="shop.html">Магазин</a><span>/</span><span>Корзина</span></nav><section class="cart-heading"><span class="eyebrow">ВАШ ВЫБОР</span><h1>Корзина</h1><p class="lead">Состав сохраняется в этом браузере. Цены и наличие требуют проверки перед оформлением.</p></section><div id="cart-storage-warning" class="store-warning" hidden></div><section class="cart-layout"><div id="cart-lines"><div class="store-empty"><h2>Корзина пока пуста.</h2><p>Выберите товары в каталоге или запросите подбор детали.</p><a class="btn btn-primary" href="shop.html">Открыть каталог ↗</a></div></div><aside class="cart-summary"><h2>Стоимость товаров</h2><p id="cart-subtotal">—</p><p id="cart-quote-status" role="status" aria-live="polite">Товары ещё не выбраны.</p><p class="muted">Доставка и дополнительные услуги не включены.</p><div class="checkout-closed"><strong>Оформление пока недоступно</strong><p>Оплата, доставка и документы будут доступны после подключения магазина. Эта корзина не создаёт заказ.</p></div><a class="store-text-link" href="${serviceLink()}">Запросить подбор ↗</a></aside></section><noscript><p class="store-warning">Сохранённую корзину можно открыть при включённом JavaScript. Подбор доступен через сервис.</p></noscript></div>`, 'cart.html'));
  files.set('store-data.json', JSON.stringify(data));
  return files;
}
